[package]
name = "mycon"
version = "0.1.0"
authors = ["olaf michaelis <o.mic@web.de>"]


[dependencies]

# serde json
serde = "1.0.69"
serde_derive = "1.0.69"
serde_json = "1.0"

# olibs = { path = "../libraries/olibs/"}
