[package]
name = "mycon"
version = "0.1.0"
authors = ["olaf michaelis <o.mic@web.de>"]


[dependencies]
clap = {version = "2.32", features = ["yaml"]}
serde = "1.0.69"
serde_yaml = "0.8"
serde_derive = "1.0"
regex = "1.0.0"
ureq = { version = "*", features = ["json", "charset"] }
