name:                  mycon
version:               "0.1.X"
author:                Olaf Michaelis <o.mic@web.de>
about:                 Mycon - provides some connection information
args:
    - check:
        short:         c
        long:          check
        help:          check ip retrieval services
        takes_value:   false
        multiple:      false
        required:      false
    - long:
        short:         m
        long:          more
        help:          more information
        takes_value:   false
        multiple:      false
        required:      false
