ip_retrieval_services:
    - http://api.ipify.org
    - http://jsonip.com
    - http://wtfismyip.com/json
    - http://ipecho.net/plain
    - http://ident.me
    - http://icanhazip.com
    - http://myip.dnsomatic.com
    - http://bot.whatismyipaddress.com
    - http://api.ipify.org?format=text

more_information: http://ip-api.com/line
tor_check_url: https://check.torproject.org/?lang=en_EN'
